file:
    upload-dir: /Desenvolvimento/backend/udemy/restfull/Upload
flyway:
    password: root
    schemas: rest_spring_boot
    url: jdbc:mysql://db:3306/
    user: root
security:
    jwt:
        token:
            expire-length: 3600000
            secret-key: secret
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: docker
        url: jdbc:mysql://db:3306/rest_spring_boot?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jackson:
        default-property-inclusion: non_null
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
