language: bash
services: docker
before_install:
  - cd SpringbootUdemy-17\ Docker/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push emfsilva/mysql-rest-spring-boot;
    docker push emfsilva/rest-spring-boot;
  on:
    branch: master
notifications:
  email: false
